-- Church Management System Database Schema
-- This script creates all tables for the church management system

-- Create BRANCH table
CREATE TABLE BRANCH (
    Branch_ID INT PRIMARY KEY AUTO_INCREMENT,
    Branch_Name VARCHAR(100) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create MEMBER table
CREATE TABLE MEMBER (
    Member_ID INT PRIMARY KEY AUTO_INCREMENT,
    Member_Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(20),
    Address VARCHAR(255),
    Email VARCHAR(100) UNIQUE,
    Password_Hash VARCHAR(255),
    Role ENUM('member', 'admin', 'pastor') DEFAULT 'member',
    Branch_ID INT,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Branch_ID) REFERENCES BRANCH(Branch_ID) ON DELETE SET NULL
);

-- Create PASTOR table
CREATE TABLE PASTOR (
    Pastor_ID INT PRIMARY KEY AUTO_INCREMENT,
    Pastor_Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(20),
    Email VARCHAR(100) UNIQUE,
    Branch_ID INT NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Branch_ID) REFERENCES BRANCH(Branch_ID) ON DELETE CASCADE
);

-- Create SERVICE table
CREATE TABLE SERVICE (
    Service_ID INT PRIMARY KEY AUTO_INCREMENT,
    Service_Type VARCHAR(100) NOT NULL,
    Service_Date DATETIME NOT NULL,
    Branch_ID INT NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Branch_ID) REFERENCES BRANCH(Branch_ID) ON DELETE CASCADE
);

-- Create DONATION table
CREATE TABLE DONATION (
    Donation_ID INT PRIMARY KEY AUTO_INCREMENT,
    Donation_Date DATETIME NOT NULL,
    Total_Amount DECIMAL(10, 2) NOT NULL,
    Member_ID INT NOT NULL,
    Branch_ID INT NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Member_ID) REFERENCES MEMBER(Member_ID) ON DELETE CASCADE,
    FOREIGN KEY (Branch_ID) REFERENCES BRANCH(Branch_ID) ON DELETE CASCADE
);

-- Create DONATION_ITEM table
CREATE TABLE DONATION_ITEM (
    DonationItem_ID INT PRIMARY KEY AUTO_INCREMENT,
    Donation_ID INT NOT NULL,
    Donation_Type VARCHAR(100),
    Amount DECIMAL(10, 2) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Donation_ID) REFERENCES DONATION(Donation_ID) ON DELETE CASCADE
);

-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
    Department_ID INT PRIMARY KEY AUTO_INCREMENT,
    Department_Name VARCHAR(100) NOT NULL,
    Leader VARCHAR(100),
    Branch_ID INT NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Branch_ID) REFERENCES BRANCH(Branch_ID) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX idx_member_branch ON MEMBER(Branch_ID);
CREATE INDEX idx_member_email ON MEMBER(Email);
CREATE INDEX idx_pastor_branch ON PASTOR(Branch_ID);
CREATE INDEX idx_service_branch ON SERVICE(Branch_ID);
CREATE INDEX idx_service_date ON SERVICE(Service_Date);
CREATE INDEX idx_donation_member ON DONATION(Member_ID);
CREATE INDEX idx_donation_branch ON DONATION(Branch_ID);
CREATE INDEX idx_donation_date ON DONATION(Donation_Date);
CREATE INDEX idx_donation_item_donation ON DONATION_ITEM(Donation_ID);
CREATE INDEX idx_department_branch ON DEPARTMENT(Branch_ID);